# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8b2158841d6ef65dfcf88bbcaa4b587a5aebb07e99c56830d94a18b065d109dd9e28eb0715b01234d88bfd0e58be0ecdea344ac05a3d75ee623039db16fdb78

test:
  secret_key_base: 18321c0d42d0b77f5b231b78f426160f34b5b4beb9bdbb4f5fb2643be319b9f6688249f4ba5512446e634a93c82ef2f5721d0808baa7814292136fba7b1fee55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
